version: '3.8'
services:
  telepiplex-core:
    container_name: telepiplex-core
    image: telepiplex-core:latest
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /to/your/path/config:/config
      - /to/your/path/tmp:/tmp
