version: '3.8'
services:
  telepiplex-media-search:
    container_name: telepiplex-media-search
    image: telepiplex-media-search:latest
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /to/your/path/config:/config
      - /to/your/path/tmp:/tmp
